// Named palette registry. Each palette maps CSS variable names (without --) to color values.
// Selectable live from Platform Configuration > Appearance Settings.
// Palette selection follows common professional admin-dashboard color-combination patterns
// (a strong primary/accent pair, a neutral surface/background scale, and semantic status colors).

export const palettes = {
  default: {
    label: 'Default (Nyusoft Orange)',
    colors: {
      'color-primary': '#FF9900',
      'color-primary-dark': '#CC7A00',
      'color-secondary': '#3D85C6',
      'color-bg': '#F7F7F8',
      'color-surface': '#FFFFFF',
      'color-border': '#E0E0E0',
      'color-text': '#1A1A1A',
      'color-text-muted': '#6B7280',
      'color-success': '#34A853',
      'color-warning': '#FBBC04',
      'color-danger': '#EA4335',
    },
  },
  ocean: {
    label: 'Ocean Blue',
    colors: {
      'color-primary': '#0B7DDA',
      'color-primary-dark': '#075EA8',
      'color-secondary': '#00A896',
      'color-bg': '#F5F8FA',
      'color-surface': '#FFFFFF',
      'color-border': '#DCE4E9',
      'color-text': '#152238',
      'color-text-muted': '#5B6B7C',
      'color-success': '#2E9E5B',
      'color-warning': '#E0A800',
      'color-danger': '#D64545',
    },
  },
  forest: {
    label: 'Forest Green',
    colors: {
      'color-primary': '#2F9E44',
      'color-primary-dark': '#25792F',
      'color-secondary': '#5C7CFA',
      'color-bg': '#F5F9F6',
      'color-surface': '#FFFFFF',
      'color-border': '#DCE9DE',
      'color-text': '#182B1E',
      'color-text-muted': '#5F7566',
      'color-success': '#2F9E44',
      'color-warning': '#F0A500',
      'color-danger': '#E03131',
    },
  },
  slate: {
    label: 'Slate Dark',
    colors: {
      'color-primary': '#6366F1',
      'color-primary-dark': '#4749B8',
      'color-secondary': '#22D3EE',
      'color-bg': '#F1F2F6',
      'color-surface': '#FFFFFF',
      'color-border': '#E2E3EA',
      'color-text': '#1E1E2E',
      'color-text-muted': '#6B6F82',
      'color-success': '#22C55E',
      'color-warning': '#F59E0B',
      'color-danger': '#EF4444',
    },
  },
  midnightIndigo: {
    label: 'Midnight Indigo',
    colors: {
      'color-primary': '#4338CA',
      'color-primary-dark': '#312995',
      'color-secondary': '#0EA5E9',
      'color-bg': '#F4F5FA',
      'color-surface': '#FFFFFF',
      'color-border': '#E2E4EF',
      'color-text': '#1B1B2F',
      'color-text-muted': '#63647E',
      'color-success': '#16A34A',
      'color-warning': '#D97706',
      'color-danger': '#DC2626',
    },
  },
  sunsetCoral: {
    label: 'Sunset Coral',
    colors: {
      'color-primary': '#F4511E',
      'color-primary-dark': '#C23F17',
      'color-secondary': '#5C6BC0',
      'color-bg': '#FBF7F5',
      'color-surface': '#FFFFFF',
      'color-border': '#EEE1DB',
      'color-text': '#2B1B15',
      'color-text-muted': '#7A6A62',
      'color-success': '#2E9E5B',
      'color-warning': '#F0A202',
      'color-danger': '#D7263D',
    },
  },
  emeraldCorporate: {
    label: 'Emerald Corporate',
    colors: {
      'color-primary': '#047857',
      'color-primary-dark': '#03543F',
      'color-secondary': '#2563EB',
      'color-bg': '#F3F8F6',
      'color-surface': '#FFFFFF',
      'color-border': '#DDEAE4',
      'color-text': '#0F2620',
      'color-text-muted': '#5D7A70',
      'color-success': '#059669',
      'color-warning': '#D97706',
      'color-danger': '#DC2626',
    },
  },
  charcoalMinimal: {
    label: 'Charcoal Minimal',
    colors: {
      'color-primary': '#18181B',
      'color-primary-dark': '#000000',
      'color-secondary': '#6366F1',
      'color-bg': '#F7F7F8',
      'color-surface': '#FFFFFF',
      'color-border': '#E4E4E7',
      'color-text': '#18181B',
      'color-text-muted': '#71717A',
      'color-success': '#16A34A',
      'color-warning': '#CA8A04',
      'color-danger': '#DC2626',
    },
  },
  royalPurple: {
    label: 'Royal Purple',
    colors: {
      'color-primary': '#7E22CE',
      'color-primary-dark': '#5B189A',
      'color-secondary': '#DB2777',
      'color-bg': '#F8F5FB',
      'color-surface': '#FFFFFF',
      'color-border': '#E7DFF0',
      'color-text': '#231830',
      'color-text-muted': '#71617F',
      'color-success': '#16A34A',
      'color-warning': '#D97706',
      'color-danger': '#DC2626',
    },
  },
  tealProfessional: {
    label: 'Teal Professional',
    colors: {
      'color-primary': '#0D9488',
      'color-primary-dark': '#0A6E64',
      'color-secondary': '#F59E0B',
      'color-bg': '#F3F9F8',
      'color-surface': '#FFFFFF',
      'color-border': '#DCEBE9',
      'color-text': '#102423',
      'color-text-muted': '#5B7674',
      'color-success': '#15803D',
      'color-warning': '#B45309',
      'color-danger': '#B91C1C',
    },
  },
  warmNeutral: {
    label: 'Warm Neutral',
    colors: {
      'color-primary': '#92400E',
      'color-primary-dark': '#6B2F0A',
      'color-secondary': '#0369A1',
      'color-bg': '#FAF7F2',
      'color-surface': '#FFFFFF',
      'color-border': '#EBE3D6',
      'color-text': '#2A2118',
      'color-text-muted': '#7C7062',
      'color-success': '#2E9E5B',
      'color-warning': '#C2760C',
      'color-danger': '#C0362C',
    },
  },
  crimsonExecutive: {
    label: 'Crimson Executive',
    colors: {
      'color-primary': '#B91C1C',
      'color-primary-dark': '#8B1414',
      'color-secondary': '#1E3A8A',
      'color-bg': '#F8F5F5',
      'color-surface': '#FFFFFF',
      'color-border': '#EBE0DF',
      'color-text': '#241414',
      'color-text-muted': '#7A6666',
      'color-success': '#15803D',
      'color-warning': '#B45309',
      'color-danger': '#B91C1C',
    },
  },
  cartBrand: {
    label: 'Brand Cart Orange',
    colors: {
      'color-primary': '#F97316',
      'color-primary-dark': '#C2570D',
      'color-secondary': '#1E293B',
      'color-bg': '#FBF8F4',
      'color-surface': '#FFFFFF',
      'color-border': '#EEE2D3',
      'color-text': '#1E1B16',
      'color-text-muted': '#78716C',
      'color-success': '#16A34A',
      'color-warning': '#D97706',
      'color-danger': '#DC2626',
    },
  },
  skyCorporate: {
    label: 'Sky Corporate',
    colors: {
      'color-primary': '#0284C7',
      'color-primary-dark': '#026394',
      'color-secondary': '#7C3AED',
      'color-bg': '#F4F9FC',
      'color-surface': '#FFFFFF',
      'color-border': '#DCEAF2',
      'color-text': '#0C2233',
      'color-text-muted': '#5E7688',
      'color-success': '#16A34A',
      'color-warning': '#D97706',
      'color-danger': '#DC2626',
    },
  },
  mintFresh: {
    label: 'Mint Fresh',
    colors: {
      'color-primary': '#059669',
      'color-primary-dark': '#047857',
      'color-secondary': '#0EA5E9',
      'color-bg': '#F2FAF7',
      'color-surface': '#FFFFFF',
      'color-border': '#DCF0E7',
      'color-text': '#0D231B',
      'color-text-muted': '#5C7A70',
      'color-success': '#059669',
      'color-warning': '#D97706',
      'color-danger': '#DC2626',
    },
  },
  steelBlue: {
    label: 'Steel Blue',
    colors: {
      'color-primary': '#475569',
      'color-primary-dark': '#334155',
      'color-secondary': '#0EA5E9',
      'color-bg': '#F5F7F9',
      'color-surface': '#FFFFFF',
      'color-border': '#E2E6EB',
      'color-text': '#1E293B',
      'color-text-muted': '#64748B',
      'color-success': '#16A34A',
      'color-warning': '#D97706',
      'color-danger': '#DC2626',
    },
  },
  roseGold: {
    label: 'Rose Gold',
    colors: {
      'color-primary': '#E11D74',
      'color-primary-dark': '#AF1659',
      'color-secondary': '#B45309',
      'color-bg': '#FDF5F8',
      'color-surface': '#FFFFFF',
      'color-border': '#F3E1E9',
      'color-text': '#2B1420',
      'color-text-muted': '#816170',
      'color-success': '#16A34A',
      'color-warning': '#D97706',
      'color-danger': '#DC2626',
    },
  },
}

export const defaultPaletteKey = 'default'
